---
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VER: "${NAUTOBOT_VER}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    dockerfile: "development/Dockerfile"
    target: "welcome_wizard-dev"
x-nautobot-base: &nautobot-base
  image: "welcome_wizard/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
  env_file:
    - "dev.env"
    - "creds.env"
  tty: true

version: "3.8"
services:
  nautobot:
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "redis"
    <<: *nautobot-build
    <<: *nautobot-base
  worker:
    entrypoint: "nautobot-server rqworker"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-base
  docs:
    build:
      args:
        NAUTOBOT_VER: "${NAUTOBOT_VER}"
        PYTHON_VER: "${PYTHON_VER}"
      context: "../"
      dockerfile: "development/Dockerfile"
      target: "docs"
    ports:
      - "8001:8080"
