# Generated by Django 3.1.12 on 2021-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome_wizard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merlin",
            name="nautobot_list_link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
