# Generated by Django 3.2.23 on 2023-11-02 19:55

from django.db import migrations

from welcome_wizard.models.merlin import Merlin


def remove_device_roles(welcome_wizard, schema):
    Merlin.objects.filter(name="Device Roles").delete()


def remove_sites(welcome_wizard, schema):
    Merlin.objects.filter(name="Sites").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("welcome_wizard", "0004_remove_manufacturerimport_slug"),
    ]

    operations = [
        migrations.RunPython(code=remove_device_roles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=remove_sites, reverse_code=migrations.RunPython.noop),
    ]
