# Generated by Django 4.2.24 on 2025-09-25 18:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome_wizard", "0006_alter_merlin_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTypeImageImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="devicetype-images")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
