# Generated by Django 4.2.24 on 2025-09-18 20:16

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome_wizard", "0006_alter_merlin_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleTypeImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("filename", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "module_type_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_types",
                        to="welcome_wizard.manufacturerimport",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
