# Generated by Django 3.1.8 on 2021-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merlin",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("all_completed", models.BooleanField(default=False)),
                ("manufacturers", models.BooleanField(default=False)),
                ("device_types", models.BooleanField(default=False)),
                ("platforms", models.BooleanField(default=False)),
                ("device_roles", models.BooleanField(default=False)),
                ("rirs", models.BooleanField(default=False)),
                ("cluster_types", models.BooleanField(default=False)),
                ("circuit_types", models.BooleanField(default=False)),
                ("providers", models.BooleanField(default=False)),
            ],
        ),
    ]
