# Generated by Django 3.1.8 on 2021-04-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merlin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merlin",
            options={"verbose_name_plural": "merlin"},
        ),
    ]
