# Generated by Django 3.1.8 on 2021-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merlin", "0002_devicetypeimport_manufacturerimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="merlin",
            name="sites",
            field=models.BooleanField(default=False),
        ),
    ]
