# Generated by Django 3.1.8 on 2021-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merlin", "0004_auto_20210422_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merlin",
            name="nautobot_add_link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="merlin",
            name="nautobot_model",
            field=models.CharField(default="", max_length=255),
        ),
    ]
